version: "3"

networks:
  test:
    external:
      name: test

services:
  cli${ORG}:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == ${NODELABEL}
    environment:
      - SYS_CHANNEL=system-channel
      - CHANNEL_NAME=${CHANNEL_NAME}
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.${NODELABEL2}.bcfm.com:${PEERPORT}
      - CORE_PEER_LOCALMSPID=${ORG}MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/peers/peer0.${NODELABEL3}.bcfm.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/peers/peer0.${NODELABEL3}.bcfm.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/peers/peer0.${NODELABEL3}.bcfm.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/users/Admin@${NODELABEL3}.bcfm.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: 
      - "/bin/bash"
      - "-c" 
      - "sleep 5 && peer channel join -b ./channel-artifacts/${CHANNEL_NAME}/${CHANNEL_NAME}.block ; ./scripts/updateAnchorPeer.sh ${CHANNEL_NAME} ${ORG}MSP orderer.bcfm.com ; sleep infinity"
    volumes:
      - /var/run/:/host/var/run/
      - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
      - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      test:
        aliases:
          - cli${NODELABEL2}.bcfm.com