version: "3"

volumes:
  peer${PEERNUMBER}${NODELABEL2}bcfmcom:

networks:
  test:
    external:
      name: test

##update couch nombres aqui y en el original
services:
  peer${PEERNUMBER}${NODELABEL}bcfmcom:
      deploy:
        placement:
          constraints:
            - node.labels.name == ${NODELABEL}
      container_name: peer${PEERNUMBER}.${NODELABEL2}.bcfm.com
      image: hyperledger/fabric-peer:2.3
      environment:
        #Generic peer variables
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        # the following setting starts chaincode containers on the same
        # bridge network as the peers
        # https://docs.docker.com/compose/networking/
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
        - FABRIC_LOGGING_SPEC=INFO
        #- FABRIC_LOGGING_SPEC=DEBUG
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        # Peer specific variabes
        - CORE_PEER_ID=peer${PEERNUMBER}.${NODELABEL2}.bcfm.com
        - CORE_PEER_ADDRESS=peer${PEERNUMBER}.${NODELABEL}.bcfm.com:${PEERPORT}
        - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEERPORT}
        - CORE_PEER_CHAINCODEADDRESS=peer0.${NODELABEL2}.bcfm.com:${CHAINCODEPORT} #peerport +1
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${CHAINCODEPORT}
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer${PEERNUMBER}.${NODELABEL}.bcfm.com:${PEERPORT}
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer${PEERNUMBER}.${NODELABEL}.bcfm.com:${PEERPORT}
        - CORE_PEER_LOCALMSPID=${ORG}MSP
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      volumes:
        - /var/run/:/host/var/run/
        - /home/ubuntu/BCFM/test-network/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/peers/peer${PEERNUMBER}.${NODELABEL3}.bcfm.com/msp:/etc/hyperledger/fabric/msp
        - /home/ubuntu/BCFM/test-network/organizations/peerOrganizations/${NODELABEL2}.bcfm.com/peers/peer${PEERNUMBER}.${NODELABEL3}.bcfm.com/tls:/etc/hyperledger/fabric/tls
        - peer${PEERNUMBER}${NODELABEL2}bcfmcom:/var/hyperledger/production
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      # command: peer node start
      ports:
        - ${PEERPORT}:${PEERPORT2}
      networks:
        test:
          aliases:
            - peer${PEERNUMBER}.${NODELABEL2}.bcfm.com

  
  