version: "3"

networks:
  test:
    external:
      name: test

services:
  cliUa:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.ua.bcfm.com:7051
      - CORE_PEER_LOCALMSPID=UaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/ua.bcfm.com/peers/peer0.ua.bcfm.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/ua.bcfm.com/peers/peer0.ua.bcfm.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/ua.bcfm.com/peers/peer0.ua.bcfm.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/ua.bcfm.com/users/Admin@ua.bcfm.com/msp
      - CHANNEL_NAME=mychannel
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: 
      - "/bin/bash"
      - "-c"
      - "sleep 30 ; ./scripts/create_app_channel.sh ; peer channel join -b ./channel-artifacts/mychannel/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel UaMSP orderer.bcfm.com ; sleep infinity" 
    volumes:
      - /var/run/:/host/var/run/
      - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
      - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    
    networks:
      test:
        aliases:
          - cliua.bcfm.com
  cliAgency:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.agency.bcfm.com:9051
      - CORE_PEER_LOCALMSPID=AgencyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/agency.bcfm.com/peers/peer0.agency.bcfm.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/agency.bcfm.com/peers/peer0.agency.bcfm.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/agency.bcfm.com/peers/peer0.agency.bcfm.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/agency.bcfm.com/users/Admin@agency.bcfm.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command:
      - "/bin/bash"
      # - "-c"
      # - "sleep 10 && peer channel join -b ./channel-artifacts/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel AgencyMSP orderer.bcfm.com ; sleep infinity" 
    volumes:
      - /var/run/:/host/var/run/
      - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
      - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      test:
        aliases:
          - cliagency.bcfm.com

  cliTransport:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.transport.bcfm.com:11051
      - CORE_PEER_LOCALMSPID=TransportMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/transport.bcfm.com/peers/peer0.transport.bcfm.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/transport.bcfm.com/peers/peer0.transport.bcfm.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/transport.bcfm.com/peers/peer0.transport.bcfm.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/transport.bcfm.com/users/Admin@transport.bcfm.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command:
      - "/bin/bash"
      # - "-c"
      # - "sleep 12 && peer channel join -b ./channel-artifacts/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel TransportMSP orderer.bcfm.com ; sleep infinity" 
    volumes:
      - /var/run/:/host/var/run/
      - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
      - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      test:
        aliases:
          - clitransport.bcfm.com

  # cliProducer:
  #   container_name: cli
  #   image: hyperledger/fabric-tools:2.3
  #   tty: true
  #   stdin_open: true
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.name == producer
  #   environment:
  #     - SYS_CHANNEL=system-channel
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=DEBUG
  #     - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
  #     # - FABRIC_LOGGING_SPEC=INFO
  #     - CC_PATH=/opt/gopath/src/github.com/chaincode
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=peer0.producer.bcfm.com:13051
  #     - CORE_PEER_LOCALMSPID=ProducerMSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/producer.bcfm.com/peers/peer0.producer.bcfm.com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/producer.bcfm.com/peers/peer0.producer.bcfm.com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/producer.bcfm.com/peers/peer0.producer.bcfm.com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/producer.bcfm.com/users/Admin@producer.bcfm.com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command:
  #     - "/bin/bash"
  #     - "-c"
  #     - "sleep 120 && peer channel join -b ./channel-artifacts/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel ProducerMSP orderer.bcfm.com ; sleep infinity" 
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
  #     - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
  #     - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
  #     - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #   networks:
  #     test:
  #       aliases:
  #         - cliProducer.bcfm.com

  # cliProvider:
  #   container_name: cli
  #   image: hyperledger/fabric-tools:2.3
  #   tty: true
  #   stdin_open: true
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.name == provider
  #   environment:
  #     - SYS_CHANNEL=system-channel
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=DEBUG
  #     - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
  #     # - FABRIC_LOGGING_SPEC=INFO
  #     - CC_PATH=/opt/gopath/src/github.com/chaincode
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=peer0.provider.bcfm.com:15051
  #     - CORE_PEER_LOCALMSPID=ProviderMSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/provider.bcfm.com/peers/peer0.provider.bcfm.com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/provider.bcfm.com/peers/peer0.provider.bcfm.com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/provider.bcfm.com/peers/peer0.provider.bcfm.com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/provider.bcfm.com/users/Admin@provider.bcfm.com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command:
  #     - "/bin/bash"
  #     - "-c"
  #     - "sleep 16 && peer channel join -b ./channel-artifacts/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel ProviderMSP orderer.bcfm.com ; sleep infinity" 
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
  #     - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
  #     - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
  #     - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #   networks:
  #     test:
  #       aliases:
  #         - cliProvider.bcfm.com

  # cliFarmacy:
  #   container_name: cli
  #   image: hyperledger/fabric-tools:2.3
  #   tty: true
  #   stdin_open: true
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.name == farmacy
  #   environment:
  #     - SYS_CHANNEL=system-channel
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - FABRIC_LOGGING_SPEC=DEBUG
  #     - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/bcfm.com/orderers/orderer.bcfm.com/msp/tlscacerts/tlsca.bcfm.com-cert.pem
  #     # - FABRIC_LOGGING_SPEC=INFO
  #     - CC_PATH=/opt/gopath/src/github.com/chaincode
  #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=peer0.farmacy.bcfm.com:17051
  #     - CORE_PEER_LOCALMSPID=FarmacyMSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/farmacy.bcfm.com/peers/peer0.farmacy.bcfm.com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/farmacy.bcfm.com/peers/peer0.farmacy.bcfm.com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/farmacy.bcfm.com/peers/peer0.farmacy.bcfm.com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/farmacy.bcfm.com/users/Admin@farmacy.bcfm.com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command:
  #     - "/bin/bash"
  #     - "-c"
  #     - "sleep 18 && peer channel join -b ./channel-artifacts/mychannel.block ; ./scripts/updateAnchorPeer.sh mychannel FarmacyMSP orderer.bcfm.com ; sleep infinity" 
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - ~/BCFM/chaincode/:/opt/gopath/src/github.com/chaincode
  #     - ~/BCFM/test-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
  #     - ~/BCFM/test-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
  #     - ~/BCFM/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #   networks:
  #     test:
  #       aliases:
  #         - cliFarmacy.bcfm.com


##hacer un fichero con parámetros que se parezca a este y se ejecute como
# docker stack deploy -c nuewvo-archivo bcfm_Cli
# este nuevo archivo tendrá nuevas constraint placements para los nuevos nodos.
# se puede hacer (probar) desde el comando update_net_peers